# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "22e57c963cb031cee6759905b7172d7c"
name = "preproduction-discount"
handle = "preproduction-discount"
application_url = "https://preproduction-discount-remix-app.vercel.app/"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"



[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/webhooks/app" 

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts, write_discounts, read_customers, read_products, read_orders"

[auth]
redirect_urls = [ "https://preproduction-discount-remix-app.vercel.app/auth/callback" ]

[pos]
embedded = false
